spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  datasource:
    username: root
    password: Th123066
    url: jdbc:mysql://localhost:3306/elementui?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: elementuser

server:
  port: 8989
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:com/team/mapper/*.xml
  type-aliases-package: com.team.entity
